### PR TITLE
👨‍💻 dont fail Dependabot Bot alerts

### PR DESCRIPTION
**Pull request by yigaldviri**

### CODE REVIEW

**Comment by idoco** [comment]
Since I don't like PRs with no emoji maybe we can add an emoji to the title automatically

Something like -
```javascript
const { Octokit } = require("@octokit/action");
const octokit = new Octokit();
const request = {
  owner: github.context.repo.owner,
  repo: github.context.repo.repo,
  pull_number: github.context.payload.pull_request.number,
  title: '🤖' + pullRequestTitle,
};
const response = await octokit.pulls.update(request);
core.info(`Response: ${response.status}`);
if (response.status !== 200) {
  core.error("Updating the pull request has failed");
} else {
  core.info(`New title: ${newTitle}`);
}
```

**Comment by yigaldviri** [comment]
The emoji in the PR is a way to the developer to express it self. An automatic emoji doesnt do that and I think is redundant.

**Comment by idoco** [comment]
Implemented a 🤖 for bot PRs

**Comment by yigaldviri** [comment]
giphy (13)

**Comment by idoco** [comment]
15B2DCD2-F554-4920-BBFE-B16B1B0DACB4

**Comment by yigaldviri** [comment]
> 15B2DCD2-F554-4920-BBFE-B16B1B0DACB4

Will always remind me Beni from Nolio

**Pull request closed without merging**
